export const tempClubs = [
  {
    id: '11',
    group: null,
    rank: 1,
    oldRank: 1,
    clubName: 'FC Arsenal',
    clubImage:
      'https://tmssl.akamaized.net/images/wappen/medium/11.png?lm=1489787850',
    points: 37,
    goals: 33,
    goalsConceded: 11,
    goalDifference: 22,
    matches: 14,
    wins: 12,
    losses: 1,
    draw: 1,
    markID: '31',
    markClass: 'meister',
    markColor: '#afd179',
    markDescription: 'Meister & UEFA-Champions-League',
  },
  {
    id: '281',
    group: null,
    rank: 2,
    oldRank: 2,
    clubName: 'Manchester City',
    clubImage:
      'https://tmssl.akamaized.net/images/wappen/medium/281.png?lm=1467356331',
    points: 32,
    goals: 40,
    goalsConceded: 14,
    goalDifference: 26,
    matches: 14,
    wins: 10,
    losses: 2,
    draw: 2,
    markID: '78',
    markClass: 'gruen',
    markColor: '#c3dc9a',
    markDescription: 'UEFA Champions League',
  },
  {
    id: '762',
    group: null,
    rank: 3,
    oldRank: 3,
    clubName: 'Newcastle Utd.',
    clubImage:
      'https://tmssl.akamaized.net/images/wappen/medium/762.png?lm=1472921161',
    points: 30,
    goals: 29,
    goalsConceded: 11,
    goalDifference: 18,
    matches: 15,
    wins: 8,
    losses: 1,
    draw: 6,
    markID: '78',
    markClass: 'gruen',
    markColor: '#c3dc9a',
    markDescription: 'UEFA Champions League',
  },
  {
    id: '148',
    group: null,
    rank: 4,
    oldRank: 4,
    clubName: 'Tottenham',
    clubImage:
      'https://tmssl.akamaized.net/images/wappen/medium/148.png?lm=1544345801',
    points: 29,
    goals: 31,
    goalsConceded: 21,
    goalDifference: 10,
    matches: 15,
    wins: 9,
    losses: 4,
    draw: 2,
    markID: '78',
    markClass: 'gruen',
    markColor: '#c3dc9a',
    markDescription: 'UEFA Champions League',
  },
  {
    id: '985',
    group: null,
    rank: 5,
    oldRank: 5,
    clubName: 'Manchester Utd.',
    clubImage:
      'https://tmssl.akamaized.net/images/wappen/medium/985.png?lm=1457975903',
    points: 26,
    goals: 20,
    goalsConceded: 20,
    goalDifference: 0,
    matches: 14,
    wins: 8,
    losses: 4,
    draw: 2,
    markID: '4',
    markClass: 'uefa',
    markColor: '#bdd9ef',
    markDescription: 'UEFA Europa League',
  },
];

export const tempSquad1 = [
  {
    height: '1,86',
    foot: 'left',
    injury: null,
    suspension: null,
    joined: 1467324000,
    contractUntil: 1719698400,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '111455',
    name: 'Granit Xhaka',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/111455-1667990175.jpg?lm=1',
    imageLarge: null,
    imageSource: 'IMAGO',
    shirtNumber: '34',
    age: 30,
    dateOfBirth: 717544800,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/granit-xhaka-fc-arsenal-2022-1642141961-78538.jpg?lm=1642141971',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '6',
        name: 'Defensive Midfield',
        shortName: 'DM',
        group: 'Midfield',
      },
      second: {
        id: '7',
        name: 'Central Midfield',
        shortName: 'CM',
        group: 'Midfield',
      },
      third: null,
    },
    nationalities: [
      {
        id: 148,
        name: 'Switzerland',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/148.png?lm=1520611569',
      },
    ],
    marketValue: {
      value: 28000000,
      currency: '€',
      progression: null,
    },
  },
  {
    height: '1,71',
    foot: 'right',
    injury: null,
    suspension: null,
    joined: 1593554400,
    contractUntil: 1719698400,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '112988',
    name: 'Cédric Soares',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/112988-1464947425.jpg?lm=1',
    imageLarge: null,
    imageSource: 'imago images',
    shirtNumber: '17',
    age: 31,
    dateOfBirth: 683589600,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/cedric-soares-fc-arsenal-2022-1668762863-96845.jpg?lm=1668762877',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '5',
        name: 'Right-Back',
        shortName: 'RB',
        group: 'Defence',
      },
      second: {
        id: '8',
        name: 'Right Midfield',
        shortName: 'RM',
        group: 'Midfield',
      },
      third: {
        id: '4',
        name: 'Left-Back',
        shortName: 'LB',
        group: 'Defence',
      },
    },
    nationalities: [
      {
        id: 136,
        name: 'Portugal',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/136.png?lm=1520611569',
      },
      {
        id: 40,
        name: 'Germany',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/40.png?lm=1520612525',
      },
    ],
    marketValue: {
      value: 4000000,
      currency: '€',
      progression: null,
    },
  },
  {
    height: '1,79',
    foot: 'right',
    injury: null,
    suspension: null,
    joined: 1452726000,
    contractUntil: 1688076000,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '160438',
    name: 'Mohamed Elneny',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/160438-1646147218.jpg?lm=1',
    imageLarge: null,
    imageSource: 'imago images',
    shirtNumber: '25',
    age: 30,
    dateOfBirth: 710805600,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/mohamed-elneny-fc-arsenal-2022-1653466566-85680.jpg?lm=1653466616',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '6',
        name: 'Defensive Midfield',
        shortName: 'DM',
        group: 'Midfield',
      },
      second: {
        id: '7',
        name: 'Central Midfield',
        shortName: 'CM',
        group: 'Midfield',
      },
      third: null,
    },
    nationalities: [
      {
        id: 2,
        name: 'Egypt',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/2.png?lm=1520611569',
      },
    ],
    marketValue: {
      value: 9000000,
      currency: '€',
      progression: null,
    },
  },
  {
    height: '1,75',
    foot: 'left',
    injury: null,
    suspension: null,
    joined: 1658440800,
    contractUntil: 1782770400,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '203853',
    name: 'Oleksandr Zinchenko',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/203853-1662666167.jpg?lm=1',
    imageLarge: null,
    imageSource: 'imago images',
    shirtNumber: '35',
    age: 26,
    dateOfBirth: 850604400,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/oleksandr-zinchenko-arsenal-fc-2022-23-1661362511-90957.jpg?lm=1661362519',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '4',
        name: 'Left-Back',
        shortName: 'LB',
        group: 'Defence',
      },
      second: {
        id: '9',
        name: 'Left Midfield',
        shortName: 'LM',
        group: 'Midfield',
      },
      third: {
        id: '7',
        name: 'Central Midfield',
        shortName: 'CM',
        group: 'Midfield',
      },
    },
    nationalities: [
      {
        id: 177,
        name: 'Ukraine',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/177.png?lm=1520611569',
      },
    ],
    marketValue: {
      value: 32000000,
      currency: '€',
      progression: null,
    },
  },
  {
    height: '1,85',
    foot: 'right',
    injury: null,
    suspension: null,
    joined: 1601848800,
    contractUntil: 1751234400,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '230784',
    name: 'Thomas Partey',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/230784-1668430877.jpg?lm=1',
    imageLarge: null,
    imageSource: 'IMAGO',
    shirtNumber: '5',
    age: 29,
    dateOfBirth: 739922400,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/thomas-partey-ghana-2022-1648587713-82864.jpg?lm=1648587721',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '6',
        name: 'Defensive Midfield',
        shortName: 'DM',
        group: 'Midfield',
      },
      second: {
        id: '7',
        name: 'Central Midfield',
        shortName: 'CM',
        group: 'Midfield',
      },
      third: null,
    },
    nationalities: [
      {
        id: 54,
        name: 'Ghana',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/54.png?lm=1520611569',
      },
    ],
    marketValue: {
      value: 38000000,
      currency: '€',
      progression: null,
    },
  },
];

export const tempSquad2 = [
  {
    height: '1,88',
    foot: 'right',
    injury: null,
    suspension: null,
    joined: 1626732000,
    contractUntil: 1688076000,
    captain: false,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '14555',
    name: 'Scott Carson',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/14555-1666733622.jpg?lm=1',
    imageLarge: null,
    imageSource: 'IMAGO',
    shirtNumber: '33',
    age: 37,
    dateOfBirth: 494546400,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/scott-carson-manchester-city-1621024483-62495.jpg?lm=1621024503',
    isGoalkeeper: true,
    positions: {
      first: {
        id: '1',
        name: 'Goalkeeper',
        shortName: 'GK',
        group: 'Goalkeeper',
      },
      second: null,
      third: null,
    },
    nationalities: [
      {
        id: 189,
        name: 'England',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
      },
    ],
    marketValue: {
      value: 250000,
      currency: '€',
      progression: null,
    },
  },
  {
    height: '1,80',
    foot: 'right',
    injury: null,
    suspension: null,
    joined: 1467324000,
    contractUntil: 1688076000,
    captain: true,
    lastClub: null,
    isLoan: null,
    wasLoan: null,
    id: '53622',
    name: 'Ilkay Gündogan',
    image:
      'https://img.a.transfermarkt.technology/portrait/medium/53622-1666733465.jpg?lm=1',
    imageLarge: null,
    imageSource: 'IMAGO',
    shirtNumber: '8',
    age: 32,
    dateOfBirth: 656722800,
    heroImage:
      'https://tmssl.akamaized.net/images/foto/normal/ilkay-gundogan-man-city-2022-1660560593-90215.jpg?lm=1660560598',
    isGoalkeeper: false,
    positions: {
      first: {
        id: '7',
        name: 'Central Midfield',
        shortName: 'CM',
        group: 'Midfield',
      },
      second: {
        id: '6',
        name: 'Defensive Midfield',
        shortName: 'DM',
        group: 'Midfield',
      },
      third: {
        id: '10',
        name: 'Attacking Midfield',
        shortName: 'AM',
        group: 'Midfield',
      },
    },
    nationalities: [
      {
        id: 40,
        name: 'Germany',
        image:
          'https://tmssl.akamaized.net/images/flagge/small/40.png?lm=1520612525',
      },
    ],
    marketValue: {
      value: 25000000,
      currency: '€',
      progression: null,
    },
  },
];
